### ISSUE TITLE
No X11 Display variable was set

### ISSUE THREAD

**Issue by G0D-Developer** [G0D-Developer/J-Tac-Toe#1]
Hey @jankeromnes 

I have trouble with setting up an X11 Display for Gitpod to run my Java GUI program. It would be great if you help me out as soon as possible. 

Thanks in advance!

**Comment by jankeromnes** [comment]
Hi @G0D-Developer! 👋 I'd recommend trying something like this:

1. Add a new file to your project called `.gitpod.yml`
2. In this file, add the line `image: gitpod/workspace-full-vnc`
3. Add and commit this file with Git
4. Push your commit to your repository

Then, close your current workspace tab, and open a new workspace. The newer workspace should have an X11 display, and a virtual desktop running on some port like 9080.

**Comment by G0D-Developer** [comment]
Hi @jankeromnes 

I can tell that my program is running, but I can't find the display. Please help me out!

Thank you!

**Comment by G0D-Developer** [comment]
Nevermind, I just refreshed and got it to work. Thank you so much @jankeromnes!
